"""empty message

Revision ID: 1e5b3861f527
Revises: 78df22effced
Create Date: 2020-05-02 23:34:03.064639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e5b3861f527'
down_revision = '78df22effced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres1', postgresql.ARRAY(sa.String(length=120)), nullable=True))
    op.drop_column('Artist', 'genres')
    op.add_column('Venue', sa.Column('genres1', postgresql.ARRAY(sa.String(length=120)), nullable=True))
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'genres1')
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'genres1')
    # ### end Alembic commands ###
