"""empty message

Revision ID: 443bbdebb386
Revises: 12ae6c06dfb1
Create Date: 2020-05-02 07:45:26.418454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443bbdebb386'
down_revision = '12ae6c06dfb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('Venue', 'genres')
    op.alter_column('Artist', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
